################################################################################
#
#                          HELICONE DEFAULT VALUES
#                     (WORKS OUT-OF-THE-BOX CONFIGURATION)
#
################################################################################

# Global configuration
global:
  # Set your domain here and it will be used throughout the chart
  domain: "your-domain.com"

# Global environment variables for all components
globalEnvVars: {}
  # S3 is always required, so we don't need to toggle it

# Helicone Application Configuration
helicone:
  # Web Frontend Configuration
  web:
    enabled: true
    image:
      repository: helicone/web
      pullPolicy: IfNotPresent
      tag: "v2025.03.05-1"
    replicaCount: 1
    service:
      type: ClusterIP
      port: 3000
    # Configure public Supabase URL
    supabasePublicUrl: "https://your-domain.com/supabase"
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls:
        - secretName: helicone-tls
          hosts:
            - "your-domain.com"
      hosts:
        - host: "your-domain.com"
          paths:
            - path: /
              pathType: ImplementationSpecific
              backend:
                serviceName: helicone-web
                servicePort: 3000
    # Database migration components
    supabaseMigrationRunner:
      enabled: true
      image:
        repository: helicone/supabase-migration-runner
        pullPolicy: IfNotPresent
        tag: "v2025.03.05-1"
    clickhouseMigrationRunner:
      image:
        repository: helicone/clickhouse-migration-runner
        pullPolicy: IfNotPresent
        tag: "v2025.03.05-1"

  # OpenAI API Proxy
  oai:
    image:
      repository: helicone/worker
      pullPolicy: IfNotPresent
      tag: "v2025.03.05-1"
    replicaCount: 1
    service:
      type: ClusterIP
      port: 8787
    # Ingress configuration for OpenAI API Proxy
    ingress:
      enabled: false
      ingressClassName: "nginx"
      annotations: {}
      tls: []
      hosts: []

  # Helicone API
  api:
    image:
      repository: helicone/worker
      pullPolicy: IfNotPresent
      tag: "v2025.03.05-1"
    replicaCount: 1
    service:
      type: ClusterIP
      port: 8787
    # Ingress configuration for Helicone API
    ingress:
      enabled: false
      ingressClassName: "nginx"
      annotations: {}
      tls: []
      hosts: []

  # ClickHouse for Analytics
  clickhouse:
    image:
      repository: clickhouse/clickhouse-server
      pullPolicy: IfNotPresent
      tag: "23.4.2.11"
    replicaCount: 1
    service:
      type: ClusterIP
      port: 8123
    persistence:
      size: 10Gi

  # Jawn Service (Gateway/Router)
  jawn:
    image:
      repository: helicone/jawn
      pullPolicy: IfNotPresent
      tag: "v2025.03.10"
    replicaCount: 1
    service:
      type: ClusterIP
      port: 8585
    publicUrl: "https://your-domain.com/jawn"
    # Set this to false to disable the prompt security validator
    extraEnvVars:
      - name: "ENABLE_PROMPT_SECURITY"
        value: "false"
    ingress:
      enabled: false
      ingressClassName: "nginx"
      annotations: {}
      tls: []
      hosts: []

################################################################################
#
#                                 SUPABASE
#
################################################################################
supabase:
  studio:
    enabled: true
    extraEnvVars:
      - name: HOSTNAME
        value: "0.0.0.0"
  storage:
    persistence:
      enabled: false
  postgresql:
    auth:
      username: "postgres"
      postgresPassword: "postgres"
  kong:
    ingress:
      enabled: false
      hostname: "supabase-your-domain.com"
    service:
      type: ClusterIP
  auth:
    image:
      repository: supabase/gotrue
      tag: v2.91.0
  jwt:
    secret: "abcdefghijklmnopqrstuvwxyz123456"
    anonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICAgInJvbGUiOiAiYW5vbiIsCiAgICAiaXNzIjogInN1cGFiYXNlIiwKICAgICJpYXQiOiAxNjc1NDAwNDAwLAogICAgImV4cCI6IDE4MzMxNjY4MDAKfQ.ztuiBzjaVoFHmoljUXWmnuDN6QU2WgJICeqwyzyZO88"
    serviceKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICAgInJvbGUiOiAic2VydmljZV9yb2xlIiwKICAgICJpc3MiOiAic3VwYWJhc2UiLAogICAgImlhdCI6IDE2NzU0MDA0MDAsCiAgICAiZXhwIjogMTgzMzE2NjgwMAp9.qNsmXzz4tG7eqJPh1Y58DbtIlJBauwpqx39UF-MwM8k"

################################################################################
#
#                          ADDITIONAL RESOURCES
#
################################################################################
extraObjects:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: helicone-services-ingress
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
        # Required for path-based routing of services
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/proxy-body-size: "100m"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    spec:
      rules:
        - host: "your-domain.com"
          http:
            paths:
              - backend:
                  service:
                    name: helicone-jawn
                    port:
                      number: 8585
                path: /jawn(/|$)(.*)
                pathType: ImplementationSpecific
              - backend:
                  service:
                    name: helicone-oai
                    port:
                      number: 8787
                path: /oai(/|$)(.*)
                pathType: ImplementationSpecific
              - backend:
                  service:
                    name: helicone-api
                    port:
                      number: 8787
                path: /api2(/|$)(.*)
                pathType: ImplementationSpecific
              - backend:
                  service:
                    name: helicone-kong
                    port:
                      number: 80
                path: /supabase(/|$)(.*)
                pathType: ImplementationSpecific
      tls:
        - hosts:
            - "your-domain.com"
          secretName: helicone-tls
