################################################################################
#
#                    HELICONE TEST DEPLOYMENT VALUES
#                      CONFIGURED FOR helicone-test.com
#
################################################################################

# Global configuration
global:
  # Using premium-rwo for GKE - this is a good default for production
  defaultStorageClass: "premium-rwo"
  storageClass: "premium-rwo"

# Global environment variables for all components
globalEnvVars:
  # Enable S3 storage for request/response bodies
  S3_ENABLED: "true"

# Helicone Application Configuration
helicone:
  # Web Frontend Configuration
  web:
    enabled: true
    image:
      repository: helicone/web
      pullPolicy: IfNotPresent
      tag: "v2025.03.05-1"
    replicaCount: 1
    service:
      type: ClusterIP
      port: 3000
    # Configured for helicone-test.com
    supabasePublicUrl: "https://helicone-test.com/supabase"
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls:
        - secretName: helicone-tls
          hosts:
            - "helicone-test.com"
      hosts:
        - host: "helicone-test.com"
          paths:
            - path: /
              pathType: ImplementationSpecific
              backend:
                serviceName: helicone-web
                servicePort: 3000
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 512Mi
    # Database migration components
    supabaseMigrationRunner:
      enabled: true
      image:
        repository: helicone/supabase-migration-runner
        pullPolicy: IfNotPresent
        tag: "v2025.03.05-1"
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 25m
          memory: 128Mi
    clickhouseMigrationRunner:
      image:
        repository: helicone/clickhouse-migration-runner
        pullPolicy: IfNotPresent
        tag: "v2025.03.05-1"
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 25m
          memory: 128Mi

  # OpenAI API Proxy
  oai:
    image:
      repository: helicone/worker
      pullPolicy: IfNotPresent
      tag: "v2025.03.05-1"
    replicaCount: 1
    service:
      type: ClusterIP
      port: 8787
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 256Mi

  # Helicone API
  api:
    image:
      repository: helicone/worker
      pullPolicy: IfNotPresent
      tag: "v2025.03.05-1"
    replicaCount: 1
    service:
      type: ClusterIP
      port: 8787
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 256Mi

  # ClickHouse for Analytics
  clickhouse:
    image:
      repository: clickhouse/clickhouse-server
      pullPolicy: IfNotPresent
      tag: "23.4.2.11"
    replicaCount: 1
    service:
      type: ClusterIP
      port: 8123
    persistence:
      size: 20Gi  # Increased from 10Gi for production workloads
      storageClass: "premium-rwo"
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 512Mi

  # Jawn Service (Gateway/Router)
  jawn:
    image:
      repository: helicone/jawn
      pullPolicy: IfNotPresent
      tag: "v2025.03.10"
    replicaCount: 1
    service:
      type: ClusterIP
      port: 8585
    # Configured for helicone-test.com
    publicUrl: "https://helicone-test.com/jawn"
    extraEnvVars:
      - name: "ENABLE_PROMPT_SECURITY"
        value: "false"
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 256Mi

################################################################################
#
#                                 SUPABASE
#
################################################################################
supabase:
  fullnameOverride: "helicone-kong"
  defaultStorageClass: "premium-rwo"
  
  # Studio Configuration
  studio:
    enabled: true
    extraEnvVars:
      - name: HOSTNAME
        value: "0.0.0.0"
    service:
      type: ClusterIP
      ports:
        http: 80
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/proxy-body-size: "100m"
      # Configured for helicone-test.com
      hostname: "studio.helicone-test.com"
      tls: true
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 256Mi
  
  # Storage Configuration
  storage:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "premium-rwo"
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 256Mi
  
  # PostgreSQL Configuration
  postgresql:
    auth:
      username: "postgres"
      postgresPassword: "postgres"
    persistence:
      enabled: true
      storageClass: "premium-rwo"
      size: 20Gi
    primary:
      persistence:
        size: 20Gi
        storageClass: "premium-rwo"
      resources:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 512Mi
  
  # Kong API Gateway Configuration
  kong:
    fullnameOverride: "helicone-kong"
    ingress:
      # Set to true if you want to expose Kong directly
      enabled: false
      # Configured for helicone-test.com
      hostname: "kong.helicone-test.com"
    service:
      type: ClusterIP
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 256Mi
  
  # Auth Configuration
  auth:
    image:
      repository: supabase/gotrue
      tag: v2.91.0
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 256Mi
  
  # Meta Service Configuration
  meta:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 256Mi
  
  # Realtime Configuration
  realtime:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 256Mi
  
  # REST Configuration
  rest:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 256Mi
  
  # JWT Configuration for API Authentication
  jwt:
    secret: "abcdefghijklmnopqrstuvwxyz123456"
    anonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICAgInJvbGUiOiAiYW5vbiIsCiAgICAiaXNzIjogInN1cGFiYXNlIiwKICAgICJpYXQiOiAxNjc1NDAwNDAwLAogICAgImV4cCI6IDE4MzMxNjY4MDAKfQ.ztuiBzjaVoFHmoljUXWmnuDN6QU2WgJICeqwyzyZO88"
    serviceKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICAgInJvbGUiOiAic2VydmljZV9yb2xlIiwKICAgICJpc3MiOiAic3VwYWJhc2UiLAogICAgImlhdCI6IDE2NzU0MDA0MDAsCiAgICAiZXhwIjogMTgzMzE2NjgwMAp9.qNsmXzz4tG7eqJPh1Y58DbtIlJBauwpqx39UF-MwM8k"

################################################################################
#
#                          ADDITIONAL RESOURCES
#
################################################################################
extraObjects:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: helicone-services-ingress
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/proxy-body-size: "100m"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    spec:
      rules:
        - host: "helicone-test.com"
          http:
            paths:
              - backend:
                  service:
                    name: helicone-jawn
                    port:
                      number: 8585
                path: /jawn(/|$)(.*)
                pathType: ImplementationSpecific
              - backend:
                  service:
                    name: helicone-oai
                    port:
                      number: 8787
                path: /oai(/|$)(.*)
                pathType: ImplementationSpecific
              - backend:
                  service:
                    name: helicone-api
                    port:
                      number: 8787
                path: /api2(/|$)(.*)
                pathType: ImplementationSpecific
              - backend:
                  service:
                    name: helicone-kong
                    port:
                      number: 80
                path: /supabase(/|$)(.*)
                pathType: ImplementationSpecific
      tls:
        - hosts:
            - "helicone-test.com"
          secretName: helicone-tls 