apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "clickhouse.name" . }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.helicone.clickhouse.persistence.storageClass }}
  storageClassName: {{ .Values.helicone.clickhouse.persistence.storageClass }}
  {{- else if .Values.global.defaultStorageClass }}
  storageClassName: {{ .Values.global.defaultStorageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.helicone.clickhouse.persistence.size | quote }}
