{{- if not .Values.helicone.clickhouse.existingDBSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.name" . }}
type: Opaque
data:
  user: {{ "helicone" | b64enc | quote }}
  password: {{ "helicone" | b64enc | quote }}
{{- end }}
